### ISSUE TITLE
`BitVec::Iter skip(n)` is `O(n)` leading to bad performance

### ISSUE THREAD

**Issue by hacatu** [contain-rs/bit-vec#122]
Consider this code:
```Rust
let v: BitVec = ...;
// original code:
v.iter().skip(start).take(len);
// updated code:
(0..len).map(|off|v[start + off]);
```

I used the original code in a program that took 75 cpu hours to run, and changing it to the updated code made it run in 3 CPU minutes.  I'm compiling with the profile
```Toml
[profile.release-trapv]
inherits = "release"
lto = "fat"
overflow-checks = true
strip = "symbols"
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-fuse-ld=mold", "-Clink-arg=-L/usr/local/lib", "-Zthreads=8"]
```
so I would certainly expect this to be optimized.

I'm using `bit-vec 0.8.0` and Rust `1.88.0-nightly (864f74d4e 2025-04-11)`

I'm not sure how much the `bit-vec` crate can do about this, but the `Iterator::skip` documentation states that `Iterator::nth` should be overridden instead of `Iterator::skip`.

`BitVec::Iter` overrides neither, so I think that it should override `nth`.  I will try to implement this and see if it works.
